language: objective-c
osx_image: xcode9.3

before_install:
  - openssl aes-256-cbc -K $encrypted_7f426862c7c1_key -iv $encrypted_7f426862c7c1_iv -in ./test/test_config.json.enc -out ./test/test_config.json -d

script:
  - carthage update HTMLSpecialCharacters MiniKeychain --platform ios --no-use-binaries
  - xcodebuild test -project reddift.xcodeproj -scheme reddift-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" CODE_SIGNING_REQUIRED=NO

branches:
  only:
  - master