language: swift
osx_image: xcode9.3

before_install:
  - cd test
  - openssl aes-256-cbc -K $encrypted_7f426862c7c1_key -iv $encrypted_7f426862c7c1_iv -in test_config.json.enc -out test_config.json -d
  - cd ../

script:
  - carthage update HTMLSpecialCharacters MiniKeychain --platform ios
  - travis_wait xcodebuild test -project reddift.xcodeproj -scheme reddift-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"